FROM node:22-bookworm-slim

# Fix the NestJS 'spawn ps ENOENT' watcher crash
RUN apt-get update && apt-get install -y procps

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app