packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@apollo/protobufjs": true
  "@google/genai": true
  "@nestjs/core": true
  "@newrelic/fn-inspect": true
  "@newrelic/native-metrics": true
  "@scarf/scarf": true
  "@swc/core": set this to true or false
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
overrides:
  react: "19.2.7"
  react-dom: "19.2.7"
  "@types/react": "19.0.8"
  "@types/react-dom": "19.0.3"
