packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@apollo/protobufjs': set this to true or false
  '@datadog/pprof': set this to true or false
  '@google/genai': true
  '@nestjs/core': true
  '@newrelic/fn-inspect': set this to true or false
  '@newrelic/native-metrics': set this to true or false
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.9.17'
  - '@turbo/darwin-arm64@2.9.17'
  - '@turbo/linux-64@2.9.17'
  - '@turbo/linux-arm64@2.9.17'
  - '@turbo/windows-64@2.9.17'
  - '@turbo/windows-arm64@2.9.17'
  - turbo@2.9.17
