packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@apollo/protobufjs": true
  "@google/genai": true
  "@nestjs/core": true
  "@newrelic/fn-inspect": true
  "@newrelic/native-metrics": true
  "@scarf/scarf": true
  "@swc/core": true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  "@welshlabs/automated-kanban-agent@git+ssh://git@github.com/WelshLabs/automated-kanban-agent.git#a484b6863aec02641fe7302f424beb6e3e6ba351": true
  "@welshlabs/automated-kanban-agent": true
  "@welshlabs/automated-kanban-agent@git+ssh://git@github.com/WelshLabs/automated-kanban-agent.git#5de6f1be4d6d18afdf06b0805448dd08c2c1af01": set this to true or false
minimumReleaseAgeExclude:
  - "@welshlabs/automated-kanban-agent@1.0.1 || 1.0.2 || 1.0.3 || 1.0.4 || 1.0.8"
overrides:
  react: "19.2.7"
  react-dom: "19.2.7"
  "@types/react": "19.0.8"
  "@types/react-dom": "19.0.3"
