# Required metadata
sonar.organization=YOUR_SONAR_ORG_KEY
sonar.projectKey=YOUR_SONAR_PROJECT_KEY

# Optional but helpful metadata
sonar.projectName=sous.tools
sonar.projectVersion=1.0

# Tells SonarCloud where the source code is
sonar.sources=.

# Tells SonarCloud to ignore the build outputs and node_modules
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/coverage/**