http:
  routers:
    dev-web:
      rule: "Host(`dev.sous.tools`) || Host(`dev.localhost`)"
      entryPoints:
        - web
        - websecure
      service: dev-web-service

    dev-api:
      rule: "Host(`dev-api.sous.tools`) || Host(`dev-api.localhost`)"
      entryPoints:
        - web
        - websecure
      service: dev-api-service

    dev-pos:
      rule: "Host(`dev-pos.sous.tools`) || Host(`dev-pos.localhost`)"
      entryPoints:
        - web
        - websecure
      service: dev-pos-service

    dev-setup:
      rule: "Host(`dev-setup.sous.tools`) || Host(`dev-setup.localhost`)"
      entryPoints:
        - web
        - websecure
      service: dev-setup-service

    storybook:
      rule: "Host(`storybook.sous.tools`) || Host(`storybook.localhost`)"
      entryPoints:
        - web
        - websecure
      service: storybook-service

    qdrant:
      rule: "Host(`qdrant.sous.tools`) || Host(`qdrant.localhost`)"
      entryPoints:
        - web
        - websecure
      service: qdrant-service

  services:
    dev-web-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

    dev-api-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"

    dev-pos-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3003"

    dev-setup-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3002"

    storybook-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3004"

    qdrant-service:
      loadBalancer:
        servers:
          - url: "http://qdrant:6333"
