const GITHUB_ID = process.env.GITHUB_ID!;
const GITHUB_SECRET = process.env.GITHUB_SECRET!;
const AUTH_SECRET = process.env.AUTH_SECRET!;

const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const IS_MOCK_ENV = process.env.IS_MOCK_ENV === 'true';
const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY =
  process.env.NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY;
const NEW_RELIC_LICENSE_KEY = process.env.NEW_RELIC_LICENSE_KEY;
const NEW_RELIC_APP_NAME = process.env.NEW_RELIC_APP_NAME;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY!;

export const config = {
    IS_MOCK_ENV,
    SUPABASE_URL: NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_ANON_KEY: NEXT_PUBLIC_SUPABASE_ANON_KEY,
    GITHUB_ID,
    GITHUB_SECRET,
    AUTH_SECRET,
    NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY,
    NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY,
    NEW_RELIC_LICENSE_KEY,
    NEW_RELIC_APP_NAME,
    GEMINI_API_KEY,
    API_BASE_URL: process.env.API_BASE_URL || process.env.NEXT_PUBLIC_API_BASE_URL,
    APP_BASE_URL: process.env.APP_BASE_URL || process.env.NEXT_PUBLIC_APP_BASE_URL,
    TV_BASE_URL: process.env.TV_BASE_URL || process.env.NEXT_PUBLIC_TV_BASE_URL,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '',
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || '',
    SQUARE_CLIENT_ID: process.env.SQUARE_CLIENT_ID || '',
    SQUARE_CLIENT_SECRET: process.env.SQUARE_CLIENT_SECRET || '',
    SQUARE_ENVIRONMENT: process.env.SQUARE_ENVIRONMENT || 'sandbox',
    PRODUCTION_SQUARE_ACCESS_TOKEN: process.env.PRODUCTION_SQUARE_ACCESS_TOKEN || '',
    SQUARE_WEBHOOK_SIGNATURE_KEY: process.env.SQUARE_WEBHOOK_SIGNATURE_KEY || '',
    USDA_FDC_API_KEY: process.env.USDA_FDC_API_KEY || '',
    NEW_RELIC_ENABLED: process.env.NEW_RELIC_ENABLED === 'true',
    PORT: process.env.PORT || 3001,
    REDIS_HOST: process.env.REDIS_HOST || '127.0.0.1',
    REDIS_PORT: parseInt(process.env.REDIS_PORT || '6379', 10),
    OLLAMA_HOST: process.env.OLLAMA_HOST || 'http://127.0.0.1:11434',
    OLLAMA_MODEL: process.env.OLLAMA_MODEL || 'llava',
    VISION_PROVIDER: process.env.VISION_PROVIDER || 'openai',
};
