const GITHUB_ID = process.env.GITHUB_ID!;
const GITHUB_SECRET = process.env.GITHUB_SECRET!;
const AUTH_SECRET = process.env.AUTH_SECRET!;

const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const IS_MOCK_ENV = process.env.IS_MOCK_ENV === 'true';
const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY =
  process.env.NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY;
const NEW_RELIC_LICENSE_KEY = process.env.NEW_RELIC_LICENSE_KEY;
const NEW_RELIC_APP_NAME = process.env.NEW_RELIC_APP_NAME;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY!;

export const config = {
    IS_MOCK_ENV,
    SUPABASE_URL: NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_ANON_KEY: NEXT_PUBLIC_SUPABASE_ANON_KEY,
    GITHUB_ID,
    GITHUB_SECRET,
    AUTH_SECRET,
    NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY,
    NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY,
    NEW_RELIC_LICENSE_KEY,
        NEW_RELIC_APP_NAME,
    GEMINI_API_KEY
};
