import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { InfisicalSDK } from "@infisical/sdk";
import * as dotenv from "dotenv";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load local .env file inside packages/config if present
dotenv.config({ path: path.join(__dirname, "../.env") });

const SECRETS_FILE_PATH = path.join(__dirname, "secrets.ts");

/**
 * Script that connects to Infisical API to retrieve environment configuration variables
 * and serializes them as a static TypeScript module file.
 */
async function sync(): Promise<void> {
  console.log("[@soustools/config] Starting secret synchronization...");

  const isMock =
    process.env.INFISICAL_MOCK === "true" ||
    process.env.NODE_ENV === "test" ||
    process.env.VITEST === "true";

  if (isMock) {
    console.log(
      "[@soustools/config] INFISICAL_MOCK=true detected. Writing mock configuration.",
    );
    const tsContent = `// Generated by secrets:sync. DO NOT EDIT.
export const secrets = {
  SUPABASE_URL: "https://placeholder-project.supabase.co",
  SUPABASE_ANON_KEY: "placeholder-anon-key-from-mock-sync",
};
`;
    fs.writeFileSync(SECRETS_FILE_PATH, tsContent, "utf8");
    console.log("[@soustools/config] Mock secrets synchronized successfully.");
    return;
  }

  const clientId = process.env.INFISICAL_CLIENT_ID;
  const clientSecret = process.env.INFISICAL_CLIENT_SECRET;
  const projectId = process.env.INFISICAL_PROJECT_ID;

  if (!clientId || !clientSecret || !projectId) {
    throw new Error(
      "Missing Infisical environment variables. " +
        "Ensure INFISICAL_CLIENT_ID, INFISICAL_CLIENT_SECRET, and INFISICAL_PROJECT_ID are set in packages/config/.env",
    );
  }

  try {
    const client = new InfisicalSDK();

    console.log(
      "[@soustools/config] Authenticating with Infisical Universal Auth...",
    );
    await client.auth().universalAuth.login({
      clientId,
      clientSecret,
    });

    console.log(
      "[@soustools/config] Authenticated successfully. Fetching secrets...",
    );

    // Retrieve all secrets for the development environment
    const secretsResponse = await client.secrets().listSecrets({
      environment: "dev",
      projectId,
    });

    const secretsArray = (secretsResponse as any).secrets || [];
    const supabaseUrl = secretsArray.find(
      (s: any) => s.secretKey === "SUPABASE_URL",
    )?.secretValue;
    const supabaseAnonKey = secretsArray.find(
      (s: any) => s.secretKey === "SUPABASE_ANON_KEY",
    )?.secretValue;

    if (!supabaseUrl || !supabaseAnonKey) {
      throw new Error(
        "Required secrets (SUPABASE_URL, SUPABASE_ANON_KEY) were not found in the Infisical project.",
      );
    }

    const tsContent = `// Generated by secrets:sync. DO NOT EDIT.
export const secrets = {
  SUPABASE_URL: ${JSON.stringify(supabaseUrl)},
  SUPABASE_ANON_KEY: ${JSON.stringify(supabaseAnonKey)},
};
`;

    fs.writeFileSync(SECRETS_FILE_PATH, tsContent, "utf8");
    console.log(
      "[@soustools/config] Secrets synchronized successfully to src/secrets.ts.",
    );
  } catch (error) {
    console.error(
      "[@soustools/config] Failed to synchronize secrets from Infisical:",
      error,
    );
    process.exit(1);
  }
}

sync().catch((err: unknown) => {
  console.error("[@soustools/config] Unhandled sync exception:", err);
  process.exit(1);
});
