import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { InfisicalSDK } from "@infisical/sdk";
import * as dotenv from "dotenv";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Vercel natively injects our secrets via the Infisical Integration.
// Do not attempt to run this file-sync script in the cloud.
if (process.env.VERCEL) {
  console.log(
    "Vercel environment detected. Generating stub secrets file for tsc...",
  );
  require("fs").writeFileSync(
    __dirname + "/secrets.ts",
    "export const secrets = process.env as any;\nexport default process.env as any;\n",
  );
  process.exit(0);
}

// Load local .env file inside packages/config if present
dotenv.config({ path: path.join(__dirname, "../.env") });

const SECRETS_FILE_PATH = path.join(__dirname, "secrets.ts");

/**
 * Script that connects to Infisical API to retrieve environment configuration variables
 * and serializes them as a static TypeScript module file.
 */
async function sync(): Promise<void> {
  console.log("[@soustools/config] Starting secret synchronization...");

  const isMock =
    String(process.env.INFISICAL_MOCK).toLowerCase() === "true" ||
    process.env.NODE_ENV === "test" ||
    process.env.VITEST === "true";

  if (isMock) {
    console.log(
      "[@soustools/config] INFISICAL_MOCK=true detected or test mode enabled. Writing mock configuration.",
    );
    const tsContent = `// Generated by secrets:sync. DO NOT EDIT.
export const secrets = {
  SUPABASE_URL: "https://placeholder-project.supabase.co",
  SUPABASE_ANON_KEY: "placeholder-anon-key-from-mock-sync",
  SUPABASE_SERVICE_ROLE_KEY: "placeholder-service-role-key-from-mock-sync",
  SQUARE_CLIENT_ID: "sandbox-sq0idb-placeholder",
  SQUARE_CLIENT_SECRET: "sandbox-sq0csp-placeholder",
  GOOGLE_CLIENT_ID: "google-client-id-placeholder",
  GOOGLE_CLIENT_SECRET: "google-client-secret-placeholder",
  PORT: 6001,
  NEW_RELIC_LICENSE_KEY: "new-relic-license-key-placeholder",
  GEMINI_API_KEY: "gemini-api-key-placeholder",
  USDA_FDC_API_KEY: "DEMO_KEY",
  VERCEL_AI_GATEWAY_API_KEY: "",
};
`;
    fs.writeFileSync(SECRETS_FILE_PATH, tsContent, "utf8");
    console.log("[@soustools/config] Mock secrets synchronized successfully.");
    return;
  }

  const clientId = process.env.INFISICAL_CLIENT_ID;
  const clientSecret = process.env.INFISICAL_CLIENT_SECRET;
  const projectId = process.env.INFISICAL_PROJECT_ID;

  if (!clientId || !clientSecret || !projectId) {
    throw new Error(
      "Missing Infisical environment variables. " +
        "Ensure INFISICAL_CLIENT_ID, INFISICAL_CLIENT_SECRET, and INFISICAL_PROJECT_ID are set in packages/config/.env",
    );
  }

  try {
    const client = new InfisicalSDK();

    console.log(
      "[@soustools/config] Authenticating with Infisical Universal Auth...",
    );
    await client.auth().universalAuth.login({
      clientId,
      clientSecret,
    });

    console.log(
      "[@soustools/config] Authenticated successfully. Fetching secrets...",
    );

    // Retrieve all secrets for the environment
    const secretsResponse = await client.secrets().listSecrets({
      environment: process.env.INFISICAL_ENV || "dev",
      projectId,
    });

    const secretsArray = (secretsResponse as any).secrets || [];

    // Default fallback values for required properties if missing
    const defaults: Record<string, any> = {
      SQUARE_CLIENT_ID: "sandbox-sq0idb-placeholder",
      SQUARE_CLIENT_SECRET: "sandbox-sq0csp-placeholder",
      GOOGLE_CLIENT_ID: "google-client-id-placeholder",
      GOOGLE_CLIENT_SECRET: "google-client-secret-placeholder",
      API_BASE_URL: "http://localhost:6001",
      APP_BASE_URL: "http://localhost:5001",
      PRODUCTION_SQUARE_ACCESS_TOKEN: "prod-square-token-placeholder",
      PORT: 6001,
      NEW_RELIC_LICENSE_KEY: "new-relic-license-key-placeholder",
      GEMINI_API_KEY: "gemini-api-key-placeholder",
      USDA_FDC_API_KEY: "DEMO_KEY",
      VERCEL_AI_GATEWAY_API_KEY: "",
    };

    const finalSecrets: Record<string, any> = { ...defaults };

    for (const secret of secretsArray) {
      if (secret.secretKey && secret.secretValue !== undefined) {
        finalSecrets[secret.secretKey] = secret.secretValue;
      }
    }

    if (!finalSecrets.SUPABASE_URL || !finalSecrets.SUPABASE_ANON_KEY) {
      throw new Error(
        "Required secrets (SUPABASE_URL, SUPABASE_ANON_KEY) were not found in the Infisical project.",
      );
    }

    const tsContentLines = [
      "// Generated by secrets:sync. DO NOT EDIT.",
      "export const secrets: Record<string, any> = {",
    ];
    for (const [key, value] of Object.entries(finalSecrets)) {
      tsContentLines.push(`  ${key}: ${JSON.stringify(value)},`);
    }
    tsContentLines.push("};", "");

    const tsContent = tsContentLines.join("\n");

    fs.writeFileSync(SECRETS_FILE_PATH, tsContent, "utf8");
    console.log(
      "[@soustools/config] Secrets synchronized successfully to src/secrets.ts.",
    );
  } catch (error) {
    console.error(
      "[@soustools/config] Failed to synchronize secrets from Infisical:",
      error,
    );
    if (fs.existsSync(SECRETS_FILE_PATH)) {
      console.log(
        "[@soustools/config] Falling back to existing secrets.ts file.",
      );
      return;
    }
    process.exit(1);
  }
}

sync().catch((err: unknown) => {
  console.error("[@soustools/config] Unhandled sync exception:", err);
  process.exit(1);
});
