export type CookIngredient={name:string;amount:number;unit:string;prep?:string}
export type CookStep={id:string;title:string;instruction:string;ingredients:CookIngredient[];timerSeconds?:number;tip?:string}
export type CookRecipe={name:string;description:string;baseYield:number;yieldUnit:string;steps:CookStep[]}
export const COOK_RECIPE:CookRecipe={name:"Mushroom Rigatoni",description:"Wild mushrooms, parmesan, brown butter",baseYield:4,yieldUnit:"portions",steps:[
{id:"s1",title:"Build the mise en place",instruction:"Bring a large pot of salted water to a rolling boil. Slice the mushrooms and finely grate the parmesan.",ingredients:[{name:"Mixed wild mushrooms",amount:450,unit:"g",prep:"cleaned and sliced"},{name:"Parmesan",amount:90,unit:"g",prep:"finely grated"}]},
{id:"s2",title:"Sear the mushrooms",instruction:"Heat a wide sauté pan until very hot. Add oil, then mushrooms in a single layer. Leave undisturbed until deeply golden before tossing.",ingredients:[{name:"Olive oil",amount:30,unit:"ml"},{name:"Mixed wild mushrooms",amount:450,unit:"g"},{name:"Kosher salt",amount:6,unit:"g"}],timerSeconds:240,tip:"Work in two batches if the pan feels crowded."},
{id:"s3",title:"Cook the pasta",instruction:"Drop the rigatoni into boiling water. Stir immediately and cook until one minute shy of al dente. Reserve pasta water.",ingredients:[{name:"Dried rigatoni",amount:400,unit:"g"},{name:"Pasta water",amount:240,unit:"ml",prep:"reserved"}],timerSeconds:600},
{id:"s4",title:"Emulsify the sauce",instruction:"Add butter and shallot to the mushrooms. Deglaze with pasta water, then add pasta and toss vigorously until glossy.",ingredients:[{name:"Unsalted butter",amount:80,unit:"g"},{name:"Shallot",amount:1,unit:"ea",prep:"finely minced"},{name:"Parmesan",amount:90,unit:"g"}],timerSeconds:180},
{id:"s5",title:"Finish and plate",instruction:"Remove from heat. Fold in herbs and lemon juice. Check seasoning and plate immediately in warm bowls.",ingredients:[{name:"Lemon juice",amount:20,unit:"ml"},{name:"Parsley",amount:15,unit:"g",prep:"chopped"},{name:"Black pepper",amount:2,unit:"g"}]}
]}
