"use client"

import { AnimatePresence, LayoutGroup, motion } from "framer-motion"
import { OmnibuttonView } from "./atoms/omnibutton.view"
import { OmnibarComposerView } from "./molecules/omnibar-composer.view"
import { OmnibarTimelineView } from "./organisms/omnibar-timeline.view"
import type { OmnibarViewActions, OmnibarViewState } from "@/lib/omnibar/types"

export function OmnibarView({ state, actions }: { state: OmnibarViewState; actions: OmnibarViewActions }) {
  if (state.home) return <div className="pointer-events-none fixed inset-0 z-20 flex w-full flex-col items-center justify-center gap-5 px-4 pt-36">{state.events.length > 0 && <motion.div aria-hidden="true" className="absolute inset-0 bg-background/82 backdrop-blur-md" initial={{ opacity: 0 }} animate={{ opacity: 1 }} />}<div className="pointer-events-auto relative w-full max-w-3xl"><OmnibarTimelineView events={state.events} onApply={actions.applyChange} onClear={actions.clearConversation} /></div><div className="pointer-events-auto relative w-full max-w-3xl"><OmnibarComposerView prompt={state.prompt} busy={state.busy} home pendingFiles={state.pendingFiles} onPromptChange={actions.setPrompt} onSubmit={actions.submitPrompt} onAttach={actions.attachDemoFiles} onVoice={actions.toggleVoice} /></div></div>
  return <LayoutGroup id="omnibar-morph"><AnimatePresence initial={false} mode="popLayout">{!state.open ? <OmnibuttonView key="omnibutton" busy={state.busy} onClick={actions.openOmnibar} /> : <motion.div key="omni-overlay" className="fixed inset-0 z-50 flex items-center justify-center px-4 py-8" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .22 }}><motion.button type="button" aria-label="Close sous chef" className="absolute inset-0 cursor-default bg-background/72 backdrop-blur-md" onClick={actions.closeOmnibar} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} /><motion.div className="relative flex max-h-full w-full max-w-3xl flex-col justify-center gap-4" initial={{ y: 10 }} animate={{ y: 0 }} exit={{ y: 8 }} transition={{ type: "spring", stiffness: 300, damping: 32 }}><AnimatePresence initial={false}>{state.events.length > 0 && <motion.div key="timeline" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 8 }} transition={{ delay: .08, duration: .2 }}><OmnibarTimelineView events={state.events} onApply={actions.applyChange} onClear={actions.clearConversation} /></motion.div>}</AnimatePresence><OmnibarComposerView prompt={state.prompt} busy={state.busy} home={false} pendingFiles={state.pendingFiles} onPromptChange={actions.setPrompt} onSubmit={actions.submitPrompt} onAttach={actions.attachDemoFiles} onVoice={actions.toggleVoice} onClose={actions.closeOmnibar} /></motion.div></motion.div>}</AnimatePresence></LayoutGroup>
}
