#!/bin/bash
# =============================================================================
# sous-ota-scheduler.sh
# Reads maintenance_window from /etc/sous/device-config.json and writes a
# systemd timer drop-in override so the OTA fires at the correct local time.
# Called at boot (or after device config changes) to keep the timer in sync.
# =============================================================================

set -euo pipefail

CONFIG_FILE="/etc/sous/device-config.json"
DROPIN_DIR="/etc/systemd/system/sous-ota.timer.d"
DROPIN_FILE="${DROPIN_DIR}/50-maintenance-window.conf"

# ── Read maintenance_window from device config ────────────────────────────────
if [ ! -f "${CONFIG_FILE}" ]; then
  echo "[ota-scheduler] Config not found: ${CONFIG_FILE} — using default 02:00"
  HOUR=2; MINUTE=0; DOW="*"
else
  HOUR="$(jq -r '.maintenance_window.hour    // 2'         "${CONFIG_FILE}")"
  MINUTE="$(jq -r '.maintenance_window.minute // 0'        "${CONFIG_FILE}")"
  DOW_RAW="$(jq -r '.maintenance_window.dayOfWeek // null' "${CONFIG_FILE}")"
fi

# ── Map dayOfWeek (0=Sun … 6=Sat) to systemd calendar day abbreviation ────────
case "${DOW_RAW:-null}" in
  null|"null") DOW_PART="*"  ;;   # Every day
  0)           DOW_PART="Sun";;
  1)           DOW_PART="Mon";;
  2)           DOW_PART="Tue";;
  3)           DOW_PART="Wed";;
  4)           DOW_PART="Thu";;
  5)           DOW_PART="Fri";;
  6)           DOW_PART="Sat";;
  *)           DOW_PART="*"  ;;
esac

# Build OnCalendar expression
# Format: [DayOfWeek] YYYY-MM-DD HH:MM:SS
if [ "${DOW_PART}" = "*" ]; then
  ON_CALENDAR="*-*-* $(printf '%02d:%02d:00' "${HOUR}" "${MINUTE}")"
else
  ON_CALENDAR="${DOW_PART} *-*-* $(printf '%02d:%02d:00' "${HOUR}" "${MINUTE}")"
fi

# ── Validate with systemd-analyze calendar ────────────────────────────────────
if ! systemd-analyze calendar "${ON_CALENDAR}" > /dev/null 2>&1; then
  echo "[ota-scheduler] WARN: Invalid calendar expression '${ON_CALENDAR}' — using fallback 02:00"
  ON_CALENDAR="*-*-* 02:00:00"
fi

# ── Write drop-in override ────────────────────────────────────────────────────
mkdir -p "${DROPIN_DIR}"
cat > "${DROPIN_FILE}" <<EODROPIN
# Auto-generated by sous-ota-scheduler.sh — do not edit manually.
# Source: ${CONFIG_FILE} maintenance_window
[Timer]
OnCalendar=
OnCalendar=${ON_CALENDAR}
EODROPIN

# ── Reload timer ─────────────────────────────────────────────────────────────
systemctl daemon-reload
systemctl restart sous-ota.timer

echo "[ota-scheduler] Timer updated → OnCalendar=${ON_CALENDAR}"
