import { Check, ChevronLeft, ChevronRight, Maximize2, Minus, Plus, ShieldCheck } from "lucide-react"
import type { CookRecipe } from "@/lib/cook/data"
import { Button } from "@/components/ui/button"
import { StepTimerContainer } from "./molecules/step-timer.container"

export function CookScreenView({recipe,stepIndex,yieldCount,completed,wakeLockActive,onYieldChange,onComplete,onPrevious,onNext,onFullscreen}:{recipe:CookRecipe;stepIndex:number;yieldCount:number;completed:Set<string>;wakeLockActive:boolean;onYieldChange:(delta:number)=>void;onComplete:()=>void;onPrevious:()=>void;onNext:()=>void;onFullscreen:()=>void}){
 const step=recipe.steps[stepIndex],scale=yieldCount/recipe.baseYield,isDone=completed.has(step.id)
 return <main className="h-dvh overflow-hidden bg-background text-foreground">
  <div className="mx-auto flex h-full min-h-0 max-w-[1500px] flex-col px-4 py-3 sm:px-6">
   <header className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Live cook mode</p><h1 className="mt-1 font-display text-xl font-semibold sm:text-2xl">{recipe.name}</h1></div><div className="flex items-center gap-2"><span className="hidden items-center gap-2 rounded-[var(--radius-sm)] border border-border bg-card px-3 py-2 text-xs text-muted-foreground sm:flex"><ShieldCheck className={wakeLockActive?"h-4 w-4 text-success":"h-4 w-4"}/>{wakeLockActive?"Screen awake":"Wake lock unavailable"}</span><Button variant="outline" size="icon" onClick={onFullscreen} aria-label="Enter fullscreen"><Maximize2 className="h-4 w-4"/></Button></div></header>
   <div className="flex items-center gap-3 py-4"><span className="text-sm text-muted-foreground">Yield</span><div className="flex items-center rounded-[var(--radius-md)] border border-border bg-card"><button onClick={()=>onYieldChange(-1)} aria-label="Decrease yield" className="p-2.5 text-muted-foreground hover:text-foreground"><Minus className="h-4 w-4"/></button><span className="min-w-24 text-center font-mono font-semibold">{yieldCount} {recipe.yieldUnit}</span><button onClick={()=>onYieldChange(1)} aria-label="Increase yield" className="p-2.5 text-muted-foreground hover:text-foreground"><Plus className="h-4 w-4"/></button></div><div className="ml-auto flex gap-1">{recipe.steps.map((item,index)=><span key={item.id} className={`h-1.5 rounded-full transition-all ${index===stepIndex?"w-8 bg-primary":completed.has(item.id)?"w-4 bg-success":"w-4 bg-muted"}`}/>)}</div></div>
   <div className="grid min-h-0 flex-1 gap-4 lg:grid-cols-[minmax(0,1fr)_360px]">
    <section className="flex min-h-0 flex-col overflow-y-auto rounded-[var(--radius-xl)] border border-border bg-card/75 p-6 shadow-sm sm:p-8 lg:p-10"><p className="font-mono text-sm text-primary">STEP {stepIndex+1} OF {recipe.steps.length}</p><h2 className="mt-3 max-w-4xl font-display text-3xl font-semibold tracking-tight sm:text-5xl">{step.title}</h2><p className="mt-6 max-w-4xl text-lg leading-relaxed text-muted-foreground sm:text-2xl sm:leading-relaxed">{step.instruction}</p>{step.tip&&<aside className="mt-7 rounded-[var(--radius-md)] border-l-2 border-accent bg-accent/8 px-4 py-3 text-sm text-foreground"><strong>Chef note:</strong> {step.tip}</aside>}<div className="mt-8">{step.timerSeconds&&<StepTimerContainer seconds={step.timerSeconds}/>}</div></section>
    <aside className="flex min-h-0 flex-col overflow-hidden rounded-[var(--radius-xl)] border border-border bg-muted/35 p-5"><div className="shrink-0"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">For this step</p><h3 className="mt-1 font-display text-xl font-semibold">Ingredients</h3></div><div className="mt-3 flex min-h-0 flex-1 flex-col divide-y divide-border overflow-y-auto pr-1">{step.ingredients.map((ingredient)=><div key={ingredient.name} className="flex items-start justify-between gap-4 py-4"><div><p className="font-medium">{ingredient.name}</p>{ingredient.prep&&<p className="mt-0.5 text-xs text-muted-foreground">{ingredient.prep}</p>}</div><p className="shrink-0 font-mono text-lg font-bold text-primary">{Number((ingredient.amount*scale).toFixed(2))} <span className="text-sm font-medium text-muted-foreground">{ingredient.unit}</span></p></div>)}</div><Button className="mt-3 w-full shrink-0" variant={isDone?"secondary":"primary"} onClick={onComplete}><Check className="h-4 w-4"/>{isDone?"Step complete":"Mark step done"}</Button></aside>
   </div>
   <footer className="mt-4 flex items-center justify-between"><Button variant="ghost" onClick={onPrevious} disabled={stepIndex===0}><ChevronLeft className="h-4 w-4"/>Previous</Button><p className="hidden text-sm text-muted-foreground sm:block">Use arrow keys to move between steps</p><Button variant="outline" onClick={onNext} disabled={stepIndex===recipe.steps.length-1}>Next step<ChevronRight className="h-4 w-4"/></Button></footer>
  </div>
 </main>
}
