name: Build and Release Signage OS Image

on:
  push:
    branches: ["main"]
    paths:
      - "deploy/pi/**"
      - "deploy/ansible/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build OS Image with pi-gen
        run: |
          cd deploy/pi/pi-gen
          sudo ./build.sh

      - name: Fetch Infisical Secrets
        uses: infisical/secrets-action@v1.0.8
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          env-slug: "prod"
          project-slug: "sous-tools-1cd-a"

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          repository: conarwelsh/signage-os
          token: ${{ env.SIGNAGE_GITHUB_PAT }}
          tag_name: v${{ github.run_number }}
          name: Signage OS v${{ github.run_number }}
          files: deploy/pi/pi-gen/deploy/*.zip
          make_latest: true
