name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Sync Docs to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/
          strategy: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}